name: tafeel_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5

  #Network
  dio: ^5.8.0+1
  #Service Locator
  get_it: ^8.0.3

  #Services
  flutter_screenutil: ^5.9.3
  logger: ^2.5.0
  logging: ^1.3.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  pretty_dio_logger: ^1.4.0
  cached_network_image: ^3.4.1

  
  easy_localization: ^3.0.7+1
  fluttertoast: ^8.2.12
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
      - assets/icons/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf

    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf

    - family: ManropeBold
      fonts:
        - asset: assets/fonts/manrope.bold.otf